from pathlib import Path

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)


BASE_DIR = Path(__file__).resolve().parent.parent
REPORT_DIR = BASE_DIR / "reports"

REPORT_DIR.mkdir(exist_ok=True)


def generate_pdf(title, dataframe, filename):

    pdf_path = REPORT_DIR / filename

    document = SimpleDocTemplate(
        str(pdf_path),
        pagesize=A4
    )

    styles = getSampleStyleSheet()

    elements = []

    elements.append(
        Paragraph(
            "Rail Sathi",
            styles["Title"]
        )
    )

    elements.append(
        Paragraph(
            "N.F. Railway Mechanical Workshop, Dibrugarh",
            styles["Heading2"]
        )
    )

    elements.append(
        Spacer(1, 20)
    )

    elements.append(
        Paragraph(
            title,
            styles["Heading1"]
        )
    )

    elements.append(
        Spacer(1, 15)
    )

    if isinstance(dataframe, pd.DataFrame):

        table_data = [
            dataframe.columns.tolist()
        ]

        table_data.extend(
            dataframe.values.tolist()
        )

        table = Table(table_data)

        table.setStyle(

            TableStyle(

                [

                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        colors.HexColor("#0B5394")
                    ),

                    (
                        "TEXTCOLOR",
                        (0, 0),
                        (-1, 0),
                        colors.white
                    ),

                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.5,
                        colors.grey
                    ),

                    (
                        "BACKGROUND",
                        (0, 1),
                        (-1, -1),
                        colors.beige
                    ),

                    (
                        "ALIGN",
                        (0, 0),
                        (-1, -1),
                        "CENTER"
                    ),

                    (
                        "FONTNAME",
                        (0, 0),
                        (-1, 0),
                        "Helvetica-Bold"
                    ),

                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, 0),
                        10
                    )

                ]

            )

        )

        elements.append(table)

    elements.append(
        Spacer(1, 20)
    )

    elements.append(

        Paragraph(

            "Generated by Rail Sathi Enterprise",

            styles["Normal"]

        )

    )

    document.build(elements)

    return pdf_path
