import sqlite3
from pathlib import Path

import pandas as pd
import streamlit as st


BASE_DIR = Path(__file__).resolve().parent.parent
DB_PATH = BASE_DIR / "database" / "railway.db"


def get_connection():
    return sqlite3.connect(DB_PATH)


def load_css():
    css_path = BASE_DIR / "css" / "style.css"

    if css_path.exists():
        with open(css_path, "r", encoding="utf-8") as file:
            st.markdown(
                f"<style>{file.read()}</style>",
                unsafe_allow_html=True
            )


def app():

    load_css()

    connection = get_connection()

    coaches = pd.read_sql_query(
        "SELECT * FROM coaches",
        connection
    )

    employees = pd.read_sql_query(
        "SELECT * FROM employees",
        connection
    )

    machines = pd.read_sql_query(
        "SELECT * FROM machines",
        connection
    )

    maintenance = pd.read_sql_query(
        "SELECT * FROM maintenance",
        connection
    )

    shops = pd.read_sql_query(
        "SELECT * FROM shops",
        connection
    )

    st.title("📄 Reports")

    st.caption(
        "Generate and export railway workshop reports."
    )

    st.divider()

    report_col1, report_col2 = st.columns(2)

    report_type = report_col1.selectbox(
        "Report Category",
        [
            "Coaches",
            "Employees",
            "Machines",
            "Maintenance",
            "Workshop Shops"
        ]
    )

    export_type = report_col2.selectbox(
        "Export Format",
        [
            "CSV",
            "Excel"
        ]
    )

    report_data = {
        "Coaches": coaches,
        "Employees": employees,
        "Machines": machines,
        "Maintenance": maintenance,
        "Workshop Shops": shops
    }

    selected_report = report_data[report_type]

    st.divider()

    total_records = len(selected_report)

    total_columns = len(selected_report.columns)

    last_updated = "Today"

    summary1, summary2, summary3 = st.columns(3)

    summary1.metric(
        "Records",
        total_records
    )

    summary2.metric(
        "Columns",
        total_columns
    )

    summary3.metric(
        "Updated",
        last_updated
    )

    st.divider()
    st.subheader("📋 Report Preview")

    search = st.text_input(
        "Search Record"
    )

    filtered_data = selected_report.copy()

    if search:

        mask = filtered_data.astype(str).apply(
            lambda column: column.str.contains(
                search,
                case=False,
                na=False
            )
        ).any(axis=1)

        filtered_data = filtered_data[mask]

    st.dataframe(
        filtered_data,
        use_container_width=True,
        hide_index=True
    )

    st.divider()

    st.subheader("📥 Export Report")

    csv = filtered_data.to_csv(
        index=False
    ).encode("utf-8")

    st.download_button(
        label="📄 Download CSV Report",
        data=csv,
        file_name=f"{report_type.lower().replace(' ', '_')}_report.csv",
        mime="text/csv"
    )

    excel_buffer = io.BytesIO()

    with pd.ExcelWriter(
        excel_buffer,
        engine="openpyxl"
    ) as writer:

        filtered_data.to_excel(
            writer,
            index=False,
            sheet_name=report_type
        )

    st.download_button(
        label="📊 Download Excel Report",
        data=excel_buffer.getvalue(),
        file_name=f"{report_type.lower().replace(' ', '_')}_report.xlsx",
        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )

    st.divider()

    st.subheader("ℹ️ Report Information")

    info1, info2 = st.columns(2)

    with info1:

        st.info(
            f"""
            **Selected Report:** {report_type}

            **Export Format:** {export_type}

            **Filtered Records:** {len(filtered_data)}
            """
        )

    with info2:

        st.success(
            f"""
            **Database:** railway.db

            **Generated By:** Rail Sathi

            **Status:** Ready for Export
            """
        )

    st.divider()
    st.subheader("📊 Report Analytics")

    analytics_col1, analytics_col2 = st.columns(2)

    with analytics_col1:

        record_chart = pd.DataFrame(
            {
                "Category": [
                    "Coaches",
                    "Employees",
                    "Machines",
                    "Maintenance",
                    "Workshop Shops"
                ],
                "Records": [
                    len(coaches),
                    len(employees),
                    len(machines),
                    len(maintenance),
                    len(shops)
                ]
            }
        )

        analytics_chart = px.bar(
            record_chart,
            x="Category",
            y="Records",
            color="Records",
            text="Records",
            title="Records Available in Each Module",
            color_continuous_scale="Blues"
        )

        analytics_chart.update_layout(
            height=430,
            plot_bgcolor="white",
            paper_bgcolor="white",
            coloraxis_showscale=False
        )

        st.plotly_chart(
            analytics_chart,
            use_container_width=True
        )

    with analytics_col2:

        export_chart = px.pie(
            values=[
                len(coaches),
                len(employees),
                len(machines),
                len(maintenance),
                len(shops)
            ],
            names=[
                "Coaches",
                "Employees",
                "Machines",
                "Maintenance",
                "Workshop Shops"
            ],
            hole=0.45,
            title="Database Distribution"
        )

        export_chart.update_layout(
            height=430
        )

        st.plotly_chart(
            export_chart,
            use_container_width=True
        )

    st.divider()

    st.subheader("📌 Report Summary")

    summary1, summary2, summary3 = st.columns(3)

    summary1.metric(
        "Available Reports",
        5
    )

    summary2.metric(
        "Export Formats",
        2
    )

    summary3.metric(
        "Total Database Records",
        len(coaches)
        + len(employees)
        + len(machines)
        + len(maintenance)
        + len(shops)
    )

    st.divider()

    st.subheader("📅 Recent Report Activity")

    activity = pd.DataFrame(
        {
            "Activity": [
                "Coach Report Generated",
                "Employee Report Exported",
                "Machine Report Generated",
                "Workshop Report Exported",
                "Maintenance Report Generated"
            ],
            "Status": [
                "Completed",
                "Completed",
                "Completed",
                "Completed",
                "Completed"
            ]
        }
    )

    st.dataframe(
        activity,
        use_container_width=True,
        hide_index=True
    )

    st.divider()

    st.caption(
        "Rail Sathi • Reports & Export Module"
    )

    connection.close()
    